# Generated by Django 4.2.3 on 2023-09-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sid', models.IntegerField()),
                ('sage', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
